### ISSUE TITLE
Uncaught Exception: FastCGI

### ISSUE THREAD

**Issue by solderdev** [owncloud/news-iOS-App#73]
Hi!

Whenever i update (drag down the list to refresh news), my owncloud server reports the following in journalctl:

`Jun 22 09:49:31 srv nginx[456]: 2016/06/22 09:49:31 [error] 12264#12264: *25835 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Session has been closed - no further changes to the session are allowed in /usr/share/webapps/owncloud/lib/private/session/internal.php:135
Jun 22 09:49:31 srv nginx[456]: Stack trace:
Jun 22 09:49:31 srv nginx[456]: #0 /usr/share/webapps/owncloud/lib/private/session/internal.php(60): OC\Session\Internal->validateSession()
Jun 22 09:49:31 srv nginx[456]: #1 /usr/share/webapps/owncloud/lib/private/session/cryptosessiondata.php(150): OC\Session\Internal->set('encrypted_sessi...', 'b8e4d0647b9ec84...')
Jun 22 09:49:31 srv nginx[456]: #2 /usr/share/webapps/owncloud/lib/private/session/cryptosessiondata.php(64): OC\Session\CryptoSessionData->close()
Jun 22 09:49:31 srv nginx[456]: #3 [internal function]: OC\Session\CryptoSessionData->__destruct()
Jun 22 09:49:31 srv nginx[456]: #4 {main}
Jun 22 09:49:31 srv nginx[456]:   thrown in /usr/share/webapps/owncloud/lib/private/session/internal.php on line 135" while reading upstream, client: 192.168.1.1, server: myhostname.com, request: "PUT /index.php/apps/news/api/v1-2/items/read/multiple HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "myhostname.com"`

Owncloud log:
`Exception: {"Exception":"OCP\\AppFramework\\Db\\DoesNotExistException","Message":"No matching entry found","Code":0,"Trace":"#0 \/usr\/share\/webapps\/owncloud\/lib\/public\/appframework\/db\/mapper.php(347): OCP\\AppFramework\\Db\\Mapper->findOneQuery('SELECT `items`....', Array, NULL, NULL)\n#1 \/usr\/share\/webapps\/owncloud\/apps\/news\/db\/itemmapper.php(82): OCP\\AppFramework\\Db\\Mapper->findEntity('SELECT `items`....', Array)\n#2 \/usr\/share\/webapps\/owncloud\/apps\/news\/db\/mysql\/itemmapper.php(67): OCA\\News\\Db\\ItemMapper->find(8307, 'chibby')\n#3 \/usr\/share\/webapps\/owncloud\/apps\/news\/service\/itemservice.php(152): OCA\\News\\Db\\Mysql\\ItemMapper->readItem(8307, true, 1466582312, 'chibby')\n#4 \/usr\/share\/webapps\/owncloud\/apps\/news\/controller\/itemapicontroller.php(177): OCA\\News\\Service\\ItemService->read(8307, true, 'chibby')\n#5 \/usr\/share\/webapps\/owncloud\/apps\/news\/controller\/itemapicontroller.php(193): OCA\\News\\Controller\\ItemApiController->setMultipleRead(true, Array)\n#6 [internal function]: OCA\\News\\Controller\\ItemApiController->readMultiple(Array)\n#7 \/usr\/share\/webapps\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#8 \/usr\/share\/webapps\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\News\\Controller\\ItemApiController), 'readMultiple')\n#9 \/usr\/share\/webapps\/owncloud\/lib\/private\/appframework\/app.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\News\\Controller\\ItemApiController), 'readMultiple')\n#10 \/usr\/share\/webapps\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('OCA\\\\News\\\\Contro...', 'readMultiple', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#11 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#12 \/usr\/share\/webapps\/owncloud\/lib\/private\/route\/router.php(276): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#13 \/usr\/share\/webapps\/owncloud\/lib\/base.php(882): OC\\Route\\Router->match('\/apps\/news\/api\/...')\n#14 \/usr\/share\/webapps\/owncloud\/index.php(39): OC::handleRequest()\n#15 {main}","File":"\/usr\/share\/webapps\/owncloud\/lib\/public\/appframework\/db\/mapper.php","Line":285} `

Additionally the Feeds are mixed up: the icons of the different sites are mixed up as well as the names. For example hackaday.com gets the logo/favicon of another site, and when i click on hackaday the news of an entirely different site show (not related to the logo).

All this does not happen in the News Webinterface.

Owncloud: 9.0.2
News: 8.8.0
nginx: 1.10.1
php: 7.0.7
mariadb: 10.1.14

Thanks,
all the best

**Comment by phedlund** [comment]
I don't believe this is an iOS app issue. What happens if you run the same command using curl or a REST client?

You should probably file an upstream bug either with News or even ownCloud core.

**Comment by solderdev** [comment]
Thank you for the reply,
as I'm not a web-developer .. how do i run the "command" using curl? i guess the command in question is
`PUT /index.php/apps/news/api/v1-2/items/read/multiple HTTP/1.1`
Isn't it nescessary for the client (curl?) to log in first??

Sry, that i'm not able to debug this on my own..

**Comment by phedlund** [comment]
Oops, the command was missing somehow:

`
curl -k -u user:pass https://example.com/owncloud/index.php/apps/notes/api/v0.2/notes
`

Replace user, pass, and domain with your information. Run it from a terminal on your computer.

**Comment by solderdev** [comment]
Running the following commands i get no output on the command line AND there is nothing logged in journalctl or owncloud log. Is that good or bad?

`curl -k -u myuser:mypw https://myserver.com/index.php/apps/notes/api/v0.2/notes`
`curl -k -u myuser:mypw https://myserver.com/index.php/apps/news/api/v1-2/items/read/multiple`

**Comment by phedlund** [comment]
Try

`
curl -k -u myuser:mypw https://myserver.com/index.php/apps/news/api/v1-2/version
`

It should return a JSON object with a version string in it.

**Comment by solderdev** [comment]
OK - that gave me the console output: {"version":"8.8.0"} - which is my news version.
No journalctl or owncloud log entries though.

**Comment by phedlund** [comment]
OK, good. I would uninstall and reinstall the CloudNews iOS app. That will delete the local database and do a fresh sync with your server. Hopefully all icons and feeds look OK after that.

**Comment by solderdev** [comment]
Thank you - will test the new installation for a few days and report back.

**Comment by solderdev** [comment]
The errors in journal and owncloud are gone after the reinstall of the app.
Icons of feeds are OK.
There is still an issue which i don't care about: now the reported "unread count" of some feeds is incorrect (too low).. But as i mentioned: that is the smallest of issues.
Thank you for your help.
